name: client
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  translator: ^1.0.3+1
  file_picker: ^10.1.9
  flutter_tts: ^4.0.2
  speech_to_text: ^7.0.0
  http: ^1.1.0
  animated_text_kit: ^4.2.2
  lottie: ^2.2.0
  flutter_audio_waveforms: ^1.1.0
  flutter_sound: ^9.2.13
  path_provider: ^2.1.1
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1
  flutter_dotenv: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/flags/indonesia.png
    - assets/flags/spain.png
    - assets/flags/america.png
    - assets/flags/japan.png
    - assets/flags/france.png
    - assets/icons/audio.png
    - assets/icons/record.png
    - assets/icons/summarize.png
    - assets/icons/summary.png
    - assets/icons/translate.png
    - assets/icons/profile.png
    - assets/icons/voxa_cat.png
    - assets/animations/voxa_cat.json
    - assets/animations/mic.json
    - assets/icons/mic_record.png
    - assets/animations/loading.json
    - images/icon.png
