name: client
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  translator: ^1.0.3+1
  file_picker: ^10.1.9
  flutter_tts: ^4.0.2
  speech_to_text: ^7.0.0
  http: ^1.1.0
  animated_text_kit: ^4.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/flags/indonesia.png
    - assets/flags/spain.png
    - assets/flags/america.png
    - assets/flags/japan.png
    - assets/flags/france.png
    - assets/icons/audio.png
    - assets/icons/record.png
    - assets/icons/summarize.png
    - assets/icons/summary.png
    - assets/icons/translate.png
    - assets/icons/profile.png
    - assets/icons/voxa_cat.png
