CREATE TABLE IF NOT EXISTS summary (
    SummaryID BIGSERIAL PRIMARY KEY,
    UserID INTEGER REFERENCES users(UserID) ON DELETE CASCADE,
    Title VARCHAR(255) NOT NULL,
    Content TEXT NOT NULL,
    CreatedAt TIMESTAMP DEFAULT NOW(),
    UpdatedAt TIMESTAMP DEFAULT NOW()
);